# Copyright Kani Contributors
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
name = "kani_macros"
version = "0.6.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full", "extra-traits", "visit", "visit-mut", "parsing", "printing"] }
quote = "1.0"
uuid = { version = "1.0", features = ["v4", "serde"] }